### ISSUE TITLE
Crash when opening Plugin or Controller Dialog

### ISSUE THREAD

**Issue by loganmc10** [m64p/mupen64plus-gui#15]
Sometimes the application will crash when opening the Plugin dialog. I've seen one report of the controller dialog too but I've never been able to reproduce that.

I can't seem to reproduce it reliably. I've never managed to get a backtrace showing where the crash is happening.

**Comment by loganmc10** [comment]
For now I did this: bcb36e0214d5d7602c6f68634bb18478e25f9234, which I believe is causing the issue. All that did was "preload" the settings if the user had never run a game before. I'll leave this open for a few days and see if I run into any more crashes

**Comment by gourdcaptain** [comment]
This reliably crashes for me when I open the controller dialogue on Arch Linux 64-bit with the official repository Mupen64plus package version 2.5-8. I've attached a stack trace generated with libSegFault, but the error seems to be occuring entirely in the mupen64plus library which I didn't compile myself, and is resisting attempts for me to compile myself with compiler errors. -_-

[mupen64plus-gui-controllercrash.txt](https://github.com/m64p/mupen64plus-gui/files/1244172/mupen64plus-gui-controllercrash.txt)

Then I tried compiling mupen64plus from the PKGBUILD script with debugging enabled and had to enable -no-pie to get the compile to work and then the config menu worked. In fact, building a non-debug build of mupen64plus with -no-pie worked fine with the controller menu.

...I have no idea whether to file an Arch Linux bug for this or not.

**Comment by loganmc10** [comment]
I'm a little confused, when you say you compiled mupen64plus, what do you mean? Do you mean libmupen64plus.so.2, if so I'm not sure what you mean by PIE enabled or disabled, it is a shared library, so it would be PIC, not PIE.

Can you share the PKGBUILD you used? I tested this on Ubuntu 17.04 but it seems fine. Does the plugin settings dialog work for you? Just not the controller dialog?

If you are able to get a backtrace with GDB it would be really helpful, I can't really tell from that stacktrace that you posted where the crash is happening

**Comment by gourdcaptain** [comment]
Oh, sorry. I compiled the mupen64plus package, which is libmupen64plus.so.2, the executable mupen64plus, and I added the -no-pie to the compiler options in the makepkg.conf file I was using to configure the build (that's an Arch-specific thing.)  I think -no-pie disables PIE and PIC.
[PKGBUILD.txt](https://github.com/m64p/mupen64plus-gui/files/1244199/PKGBUILD.txt) - There's the PKGBUILD, but again, arch-specific. 

The plugin dialog works either with the standard or "-no-pie" compiler option build.

Trying the GCC stacktrace now.

**Comment by gourdcaptain** [comment]
[mupen64plus-gui-gdbbacktrace.txt](https://github.com/m64p/mupen64plus-gui/files/1244229/mupen64plus-gui-gdbbacktrace.txt)
Does this backtrace work better?

**Comment by loganmc10** [comment]
I installed Arch Linux in a VM to test this out. I don't think it has anything to do with PIE or no PIE. I believe it's because the version of mupen64plus included in Arch is linked against SDL 1.2, but this GUI is linked against SDL2. When you compile it yourself, it is probably linking against SDL2 (you can check by doing an ```ldd``` on libmupen64plus.so.2

I compiled mupen64plus from source and it worked, but I also experienced the same as you, the version from pacman crashes. It actually crashes in the plugin and controller dialog for me.

There is probably not much I can about this if the SDL thing is really the problem, besides adding a note to the GitHub page that you need to use a version of mupen64plus linked against SDL2.

**Comment by gourdcaptain** [comment]
Ah, okay. Thanks for figuring it out, and that's a good thing to put up. I'll just compile a copy of mupen64plus in my home directory for this.

**Comment by loganmc10** [comment]
Yeah hopefully the mupen64plus team will release a new version sometime this year, 2.5 is pretty old, although I think it still technically supports SDL 1.2, but SDL2 should be the default

I added a note to the README https://github.com/m64p/mupen64plus-gui/commit/3279de2755eb7e12cb81cd73938329e405ad21c3

**Comment by gourdcaptain** [comment]
And yep, just built a copy of mupen64plus-git from the Arch User Repository PKGBUILD and installed it systemwide and that worked without modding the script (seeing as how that script's actually been tweaked to work with the current standard Arch compiler settings), and it's built against SDL2.

**Comment by loganmc10** [comment]
Yeah so potentially Arch could re-build their mupen64plus package and link it against SDL2 (like right now their version is ```2.5-8```, they could make a ```2.5-9``` and link it against SDL2 instead of SDL1.2)

**Comment by loganmc10** [comment]
Honestly though 2.5 is around 2 years old, a lot has changed since then. The git version is very stable, you're much better off using the git version
