### ISSUE TITLE
Set directories before launch

### ISSUE THREAD

**Issue by ibrokemypie** [m64p/mupen64plus-gui#16]
I am attempting to package this for the aur, while keeping mupen64plus compat, so have put the files included with the binary zip in /usr/share/m64p, however when launching, it is unable to detect the correct core and plugin dirs, causing crash on startup until manually resolved. Is there any way to set the defaults of these on a system level?

**Comment by loganmc10** [comment]
I'll need some help on this, can you post the contents of the gui.conf it creates?

It should be in ~/.config/mupen64plus/gui.conf

It should search through /usr/lib and /usr/local/lib for the directories. Anyway can you maybe delete gui.conf, then open mupen64plus-gui, then post the contents of gui.conf that it creates? That will help me narrow down the problem

**Comment by ibrokemypie** [comment]
turns out I wasnt putting things in the right directories, that works now, however it detects /usr/lib/libmupen64plus.so.2 as the core library pather, rather than the correct one, so crashes when loading a rom

**Comment by loganmc10** [comment]
what is the correct path? That looks right to me

**Comment by ibrokemypie** [comment]
/usr/lib/m64p/libmupen64plus.so.2.0.0
any others crash

**Comment by loganmc10** [comment]
Something seems wrong with your installation. if /usr/lib/libmupen64plus.so.2 exists, it should work, and it should be a symlink to /usr/lib/libmupen64plus.so.2.0.0

If you don't want it to use /usr/lib/libmupen64plus.so.2, then you should delete that file, if it doesn't exist, it should keep searching through /usr/lib until it finds /usr/lib/m64p/libmupen64plus.so.2

It does look for libmupen64plus.so.2, not libmupen64plus.so.2.0.0:
https://github.com/m64p/mupen64plus-gui/blob/master/osal/osal_preproc.h#L60

**Comment by loganmc10** [comment]
@ibrokemypie  This is likely the same issue as https://github.com/m64p/mupen64plus-gui/issues/15

The mupen64plus package included in Arch is linked against SDL1.2, and thus is not compatible with mupen64plus-gui, which requires SDL2

**Comment by Jakecheslekov** [comment]
I'm having an identical issue on Void Linux, works great on Arch Linux though!
