### ISSUE TITLE
Controller Configuration

### ISSUE THREAD

**Issue by loganmc10** [m64p/mupen64plus-gui#2]

**Comment by loganmc10** [comment]
I've started on this, should be done by the end of the week

**Comment by loganmc10** [comment]
Closed by 09e710b4025a70e64e434c17bca6c07b99400544, could use some testing/feedback

**Comment by fprimex** [comment]
Got around to making a new build today. It works good with my Xbox One bluetooth controller on my Mac in manual mode. Not sure if this is a known problem/limitation, but setting automatic with the Xbox controller doesn't provide any controller input that I've seen yet. Haven't tried with the Saitek yet, but I doubt that is a big deal.

**Comment by loganmc10** [comment]
Yeah it's going to depend on the controller. The auto config happens via this file:

https://github.com/mupen64plus/mupen64plus-input-sdl/blob/master/data/InputAutoCfg.ini

I have an Xbox One controller, and on Linux it shows up as "Microsoft X-Box One pad" and the auto config works, on Windows it shows up as "XInput: XInput Controller #1", and it doesn't work. It's just going to depend on the controller. All that is handled by the input plugin though

**Comment by fprimex** [comment]
Might be worth providing some platform specific configs.

**Comment by loganmc10** [comment]
Yeah I haven't looked into it much, but ```XInput: XInput Controller #1``` is basically "Generic Controller", so I don't know how SDL (which handles the joysticks) would differentiate between an Xbox 360 controller and an Xbox One controller if the systems reports them both as ```XInput Controller```. Maybe if I installed some Xbox One Controller drivers or something on Windows it would show up right? I just plugged it in and it connected so I didn't go searching for drivers.

**Comment by fprimex** [comment]
> Maybe if I installed some Xbox One Controller drivers or something on Windows it would show up right?

They are built into Windows 10. I did not need to install drivers on either Windows 10 or on MacOS 10.12.3. Mine is the bluetooth one.
