### ISSUE TITLE
Audio Device Selection (and possibly display)

### ISSUE THREAD

**Issue by bloodlvst** [m64p/mupen64plus-gui#21]
Is there any way this could be added?

My system running m64p is my daily desktop rig, but I also run Kodi on my 3rd display (which is my living room TV). I can use Kodi to launch m64p via command-line parameters, but it will default to the main display and also use the default device (instead of the HDMI audio.

It would be great to be able to specify at least the audio device so I don't have to constantly change the default device should someone else want to use the emulator while I'm using the system. If this can be considered it'd be most appreciated!

**Comment by loganmc10** [comment]
If this was to be implemented, it would have to be implemented in the audio plugin:

https://github.com/mupen64plus/mupen64plus-audio-sdl

In Linux you can select an output device for each application in the OS level, and I know in Windows there are 3rd party tools that allow it. That is probably the easier route.

I believe SDL2 allows you to specify the audio device, so it's possible for the audio plugin to do this, but the mupen64plus config system isn't really setup well to handle this kind of thing.

**Comment by loganmc10** [comment]
@bloodlvst I implemented this in https://m64p.github.io, but it's not extremely intuitive, here are the instructions:

If you open a game, and go to Emulation -> View Log, you'll see something like this:

![capture](https://user-images.githubusercontent.com/848146/30617365-f857499c-9d52-11e7-8f27-c9faf76d0977.PNG)

You'll see on my computer it lists "Audio Device 0" (bluetooth speaker) and "Audio Device 1" (regular speaker).

Then you go Settings->Core and Plugin Settings->Audio Plugin

There is an option called AUDIO_DEVICE, it defaults to -1, which means the system default, but you can change it to 0,1,2, etc... whatever number corresponds to the device you see in the log file that you want.

Hopefully this solves your issue
