### ISSUE TITLE
Controller Plugin Selection

### ISSUE THREAD

**Issue by BatteryPine** [m64p/mupen64plus-gui#22]
Can this feature be added? It's a bit annoying having to edit mupen64plus-gui.ini manually when I want to use raphnet's raw input plugin.

**Comment by loganmc10** [comment]
Yep this is definitely possible. Are there configuration options for the raphnet plugin? Like would you expect to be able to configure the plugin alongside the video/audio/RSP plugin?

Right now the "controller setup" dialog is specific to input-sdl, but I could potentially add a "controller" section to the regular plugin settings dialog if a different input plugin was in use.

**Comment by BatteryPine** [comment]
The raphnet plugin doesn't have configuration options and it's supposed to be used with raphnet's N64 adapters. It makes the emulator work directly with the N64 controller. There's a GitHub repository for the plugin and a link to the plugin's homepage explaining more about what the plugin does. https://github.com/raphnet/mupen64plus-input-raphnetraw

**Comment by loganmc10** [comment]
I understand what the plugin does, I just wasn't sure if it put any configuration options in mupen64plus.cfg

It sounds like it doesn't so that makes it easier.

**Comment by loganmc10** [comment]
Ok this has been implemented, you can choose the controller plugin just like the other plugins
