### ISSUE TITLE
Hotkey for Hard Reset and Toggle Speed Limiter

### ISSUE THREAD

**Issue by BatteryPine** [m64p/mupen64plus-gui#23]
Can there be a hotkey for these two options? It's a bit annoying having to exit fullscreen mode and entering it again when there's a long unskippable sequence I've already seen. Maybe F8 for Hard Reset and F4 or the Tab key for Toggle Speed Limiter.

**Comment by loganmc10** [comment]
I don't have my computer on me right now, but have your tried holding F to fast forward? It should play the game at 250% speed I believe (while F is held down)

I don't think hard reset works properly in mupen64plus, I wouldn't advise using it, but I believe F9 is the shortcut for a soft reset

**Comment by BatteryPine** [comment]
Holding down F does speed up the game.
