### ISSUE TITLE
[Request] -nogui command line argument

### ISSUE THREAD

**Issue by tony971** [m64p/mupen64plus-gui#24]
This functionality helps launcher users. The command line arguments are good enough to start a game, but hitting escape only closes the rendering window, not the gui. So users aren't returned to the launcher menu from exiting a game. (This becomes annoying when exclusively using a controller.)

**Comment by loganmc10** [comment]
So to be clear: launching in this mode would hide the menu bar and close the application when the game ends, correct?

**Comment by tony971** [comment]
Correct. PCSX2 has an implementation of this.

https://wiki.pcsx2.net/Command-line_support#General_Options

**Comment by tony971** [comment]
Although, hiding the menu bar isn't as important as closing the application on emulation shutdown. So even if you did something as simple as dolphin's [-b command](https://wiki.dolphin-emu.org/index.php?title=Command_Line_Options), it would solve the main issue.

**Comment by loganmc10** [comment]
Ok this has been implemented, ```mupen64plus-gui.exe --nogui /path/to/rom.n64``` will now hide the GUI elements, and close the application when the game ends

**Comment by tony971** [comment]
Thanks! I'll test it out tonight.

**Comment by tony971** [comment]
Works as intended!
