### ISSUE TITLE
Can't access m64p log.

### ISSUE THREAD

**Issue by AmbientMalice** [m64p/mupen64plus-gui#25]
This seems like a bit of an oversight. I need to access to the m64p log to check the game's CRC and such, and I can't do this with your GUI.

**Comment by loganmc10** [comment]
This is is an oversight, you can see the logs if you launch it from Linux via the command line (which is how I do it), but not in any other case, so it's sort of a case of "it works for me!". I'll correct this and add a way to view the log via the GUI.

**Comment by loganmc10** [comment]
Ok this has been implemented. Under the "Emulation" menu at the bottom is a "View Log" option.

**Comment by AmbientMalice** [comment]
Thanks, man.
