### ISSUE TITLE
Controller Dialog Improvements

### ISSUE THREAD

**Issue by loganmc10** [m64p/mupen64plus-gui#26]
Just a bit of a todo list for myself:

- Add "Bind All" option in controller dialog

**Comment by AmbientMalice** [comment]
Would it be possible to add mouse support? Because quite a few N64 games benefit from being able to bind the mouse to the analogue stick.

**Comment by loganmc10** [comment]
Have you tried the "mouse" checkbox? That should map the mouse to the analog stick

**Comment by AmbientMalice** [comment]
>Have you tried the "mouse" checkbox? That should map the mouse to the analog stick

Yes, I have, and it doesn't seem to do anything.

**Comment by loganmc10** [comment]
Ok, I've never tried it, I'll play around with that this week

**Comment by loganmc10** [comment]
I just looked into the mouse a bit more. It's not going to work. It uses SDL to capture the mouse inputs, and mupen64plus-gui doesn't create an SDL window (it uses Qt). The input plugin would need a fairly major re-working to accept mouse inputs from outside sources like Qt. I might look into it one day, but not soon.

I removed the mouse items from the controller dialog to avoid confusion

**Comment by AmbientMalice** [comment]
That's a shame. Another issue I've noticed is the GUI doesn't seem to handle Xbox 360 knockoff controllers very well. The right analogue stick registers as the left analogue stick.

**Comment by loganmc10** [comment]
You mean the autoconfig? Does it work when you manually map it?

The auto configs are handled by this file:

https://github.com/mupen64plus/mupen64plus-input-sdl/blob/master/data/InputAutoCfg.ini

It doesn't receive a lot of love. Also, Windows and Linux seem to behave differently. My Xbox One controller auto configs properly in Linux, but it's all wrong in Windows. Since most the mupen64plus devs use Linux, there is probably a bias towards that setup. It's all handled by SDL, so I don't know why SDL seems to treat them differently based on the OS.

**Comment by AmbientMalice** [comment]
>Does it work when you manually map it?

Manual mapping. It basically refuses the map the right stick correctly. I suppose I could probably fix the issue by using a 360 controller emulator.

**Comment by loganmc10** [comment]
> Manual mapping is what I was doing. It basically refuses the map the right stick correctly. I suppose I could probably fix the issue by using a 360 controller emulator.

Oh I understand. So both analogue sticks register as the same stick? Yeah I'm not really sure what could be done about that, it just uses SDL2 to gather the gamepad inputs, so it's actually SDL2 that is registering them both as the same thing.
