### ISSUE TITLE
Getting a handful of Qt related errors on Ubuntu based elementaryOS- suggestions to fix?

### ISSUE THREAD

**Issue by Weej1** [m64p/mupen64plus-gui#29]
Hi, 
I've installed `qt5-default` as in the readme. but I'm still getting these errors:
```
./mupen64plus-gui: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by ./mupen64plus-gui)
./mupen64plus-gui: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by ./mupen64plus-gui)
./mupen64plus-gui: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.7' not found (required by ./mupen64plus-gui)
./mupen64plus-gui: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by ./mupen64plus-gui)
```
According to `apt` I have Qt ver. 5.5.1, the readme states Qt 5.4, one of the error messages above is asking for `Qt_5.7` - and now I'm just wondering what exactly I need to do to get this running. Any suggestions on which exact package for Qt is needed here?

**Comment by loganmc10** [comment]
Did you compile it yourself? If not, where did you get the build from?

**Comment by loganmc10** [comment]
I'm assuming you're using the binary build from m64p.github.io

If so, that is built on Debian Stretch, which includes Qt 5.7, if you want to use an older version of Qt, you'll probably have to compile this package yourself

**Comment by Weej1** [comment]
HI @loganmc10 
You're right, I got the binary build from m64p.github.io. My apologies I didn't realize they led to 2 separate projects. I'll try compiling and if its successful, will close this issue.

**Comment by loganmc10** [comment]
Please re-open if this still an issue
