### ISSUE TITLE
Adding Mupen icon 

### ISSUE THREAD

**Issue by Papermanzero** [m64p/mupen64plus-gui#32]
Would be nice to add the mupen plus icon as application icon
https://mupen64plus.org

**Comment by loganmc10** [comment]
Yes I'll hopefully get around to this sometime this week

**Comment by StenApp** [comment]
pulled a request for a Mac icon

**Comment by loganmc10** [comment]
Fixed by https://github.com/m64p/mupen64plus-gui/commit/2015343176253fefae32b2417f57c56e512ea52f
