### ISSUE TITLE
Toggle fullscreen broken on macOS?

### ISSUE THREAD

**Issue by StenApp** [m64p/mupen64plus-gui#35]
Mysterious, toggle fullscreen is broken (alt+return) if no rom is run.
If a rom is running, it works. Is this intended?
Go to fullscreenmode is usually done by control+command+F under macOS.

**Comment by loganmc10** [comment]
Yes this is expected. Fullscreen toggle only happens during emulation. In the config options under "Video-General" is an option for "Fullscreen", which will make games start in fullscreen
