### ISSUE TITLE
[macOS] Save config issue

### ISSUE THREAD

**Issue by StenApp** [m64p/mupen64plus-gui#37]
Hey there,

 please tune the Gui that it saves the ini file under macOS in
`~/Library/Application Support/mupen64plus`

and NOT in the app bundle under `mupen64plus-gui.app/Contents/MacOS`

**Comment by loganmc10** [comment]
I've had requests in the past to have the INI file stored along with the executable, in order to make it portable (https://github.com/m64p/mupen64plus-gui/issues/17).

The way it currently works allows a users to have multiple copies of the application on their machine with different configurations, or transfer the application to a different machine and keep the configuration.

**Comment by scottluker** [comment]
Keeping the executable and config file is best for most users.

**Comment by StenApp** [comment]
I got it, but.
Can you fix the standard Mac config path:

Core and plugins from `mupen64plus-gui.app/Contents/MacOS` to
`mupen64plus-gui.app/Contents/Frameworks`

with my build.sh patch they get copied there

**Comment by loganmc10** [comment]
> @loganmc10 Why don't you make a build switch: portable?

There is no downside to the portable build. There is no reason to have a version that stores the INI file in a system folder.

**Comment by StenApp** [comment]
These are no system paths, those are app bundle paths

**Comment by fprimex** [comment]
I ran into issues having things in the bundle's `Frameworks` directory that had a lot to do with library loading. If anyone can get it working then great, but I couldn't.

I'm in agreement about saving to user directories for the long term, but if that's not the plan now then, yeah, stuff _should_ go in `Frameworks` if anyone can get it working.

Paths like `~/Library/Application Support/mupen64plus` on Mac are the equivalent of things like `~/.mupen64plus` on Linux. So any work that you do to make this able to be packaged into something like an RPM or DEB or whatnot would apply.

**Comment by fprimex** [comment]
Sorry, not saying the INI should go in `Frameworks`; I mean the dylibs and whatnot. If the INI is not going to go into the user's home dir then it should _probably_ go in... `Content/Resources`?

**Comment by StenApp** [comment]
```
-  find mupen64plus -type f -depth 1 \
 -    -exec mv {} mupen64plus/mupen64plus-gui.app/Contents/MacOS/ \;
 +  mkdir -p mupen64plus/mupen64plus-gui.app/Contents/Frameworks
 +  find ./mupen64plus -name "*mupen64plus*.dylib" -depth 1 \
 + -exec mv {} mupen64plus/mupen64plus-gui.app/Contents/Frameworks/ \;
 +
 +  mkdir -p mupen64plus/mupen64plus-gui.app/Contents/Resources
 +  find ./mupen64plus -type f -depth 1 \
 + -exec mv {} mupen64plus/mupen64plus-gui.app/Contents/Resources/ \;
```

Thats my code change

**Comment by StenApp** [comment]
Made changes to point mupen64plus-gui to Resources folder which contains with my build.sh the ini

**Comment by StenApp** [comment]
@loganmc10  What does the option configDir in the Gui mean?
Where the Gui places its config? Or the Mupen64Plus core user Dir?

**Comment by loganmc10** [comment]
The "Config Dir Path" setting in the GUI is the path to mupen64plus.cfg.

The GUI places its config (mupen64plus-gui.ini) in the folder as the executable, this is hard-coded:

https://github.com/m64p/mupen64plus-gui/blob/master/mainwindow.cpp#L259-L260

**Comment by StenApp** [comment]
Thanks for the information.
It is not easy to get a real Mac app, because when the Core saves its stuff in /Users/currentuser/Library/Application Support/Mupen64Plus/
and the build script bundles it to the app then the inis and cfgs are in /whereverthe/bundleis/mupen64plus-gui.app/Contents/Resources.

Something has to copy it to the config path....
Have it in the app bundle is possible but better in the Mupen64Plus folder in Application Support....

**Comment by StenApp** [comment]
Broken64Plus

**Comment by loganmc10** [comment]
Like I've mentioned in the past, none of the developers (myself included) own or use a Mac. It works very well in Linux and Windows because we can test those systems. Until someone with some programming skills steps up to improve Mac support, it's not going to change, no matter how many issues are opened or closed.
