### ISSUE TITLE
[macOS] Filepaths corrected first try

### ISSUE THREAD

**Issue by StenApp** [m64p/mupen64plus-gui#38]
@loganmc10 

I'm not able to change the osal file that it looks in the Mac app bundle:

https://github.com/mupen64plus/mupen64plus-core/pull/495/files#diff-371e8a27826f75016d583f1a4d73c264

maybe you can simplify the osal_files_unix.c and create a osal_files_macos.c

**Comment by loganmc10** [comment]
I just copied those files from mupen64plus-ui-console, I don't have a Mac, or any real understanding of the OS X filesystem. Any change I make would be me "working blind", I don't plan on working on anything related to Mac/OS X

**Comment by StenApp** [comment]
I'd like to change your code but I don't understand it completely, the only I can do is give you more information about the filesystem and the app bundle.

https://github.com/mupen64plus/mupen64plus-core/issues/484

**Comment by fprimex** [comment]
One thing I noticed after I made the bundle change is that it's not possible to actually load the plugins, it seems. I wiped my old configuration and you get the "choose a plugin" window, but can't descend into the bundle to pick them.

I think we should keep them in the bundle, but load the plugins as the defaults when the program is first run. Then add a button to reset the settings to the defaults because it's not possible to pick the items in the bundle. I feel we can either do this just for MacOS, or decide if it would be useful for all platforms (I think it would be; sometimes after monkeying with too many things it's nice to start over).

**Comment by fprimex** [comment]
(if it's not clear from my comment, I made the initial bundle structure, so if it's messed up I'm to blame for that one ;) )

**Comment by StenApp** [comment]
Hi, nice to meet you. I tried to continue your work.

The dylibs are in the bundle under contents/Frameworks, the executable is under contents/Macos and the ini files are under resources with my pull request build file.

using QString QCoreApplication::applicationDirPath()
shows you the path to location of application bundle +"Contents/macOS/"

we need to change the Gui function to look in the framework folder.

**Comment by fprimex** [comment]
Commented on the PR. You're right about the directory structure but as I said over there I couldn't get it working. The bundle ended up being a mix of "structured like Mac" and "runs like Linux". As you my tell from my responsiveness I unfortunately don't have a ton of time right now to contribute, but I feel like you're on the right track.

As far as the objective-c stuff goes, I agree with not wanting to deal with it! I was hoping there would be some way to tell a Qt file/open dialog to allow descending into app bundles but it was not to be so.

I still feel like putting all of those paths in, loading them as defaults, and adding a 'Reset' button avoids the whole mess, plus is something that works on every platform.

**Comment by StenApp** [comment]
My idea is to change the  gui load paths which contain QCoreApplication::applicationDirPath()

> QString QCoreApplication::applicationDirPath()
> 
> Returns the directory that contains the application executable.
> 
> For example, if you have installed Qt in the C:\Qt directory, and you run the regexp example, this function will return "C:/Qt/examples/tools/regexp".
> 
> On macOS and iOS this will point to the directory actually containing the executable, which may be inside an application bundle (if the application is bundled).

if we use the path of the bundle running and add "Contents/macOS/" then it sould point to the dylibs.

**Comment by StenApp** [comment]
Maybe anyone can fix this, affected files are attached

```
/Users/stenapp/mupen64plus-GLideN64/mupen64plus-gui/interface/plugin.cpp:129:44: error: 'QString' does not refer to a value
        lib_filelist = osal_library_search(QString pluginDir(bundlePath).append("/Contents/Frameworks/"));
                                           ^
/usr/local/Cellar/qt/5.10.0/lib/QtGui.framework/Headers/qwindowdefs.h:79:7: note: declared here
class QString;
      ^
1 error generated.
make: *** [plugin.o] Error 1
make: *** Waiting for unfinished jobs....
/Users/stenapp/mupen64plus-GLideN64/mupen64plus-gui/interface/core_interface.cpp:154:99: error: 'QString' does not refer to a value
            rval = (*CoreStartup)(CORE_API_VERSION, qtConfigDir.toLatin1().data() /*Config dir*/, QString coreDir(bundlepath).append("/Contents/Frameworks/"), (char*)"Core", DebugCallback, NULL, NULL);
                                                                                                  ^
/usr/local/Cellar/qt/5.10.0/lib/QtCore.framework/Headers/qmetatype.h:1926:1: note: declared here
QT_FOR_EACH_STATIC_CORE_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
^
/usr/local/Cellar/qt/5.10.0/lib/QtCore.framework/Headers/qmetatype.h:94:20: note: expanded from macro 'QT_FOR_EACH_STATIC_CORE_CLASS'
    F(QString, 10, QString) \
                   ^
/Users/stenapp/mupen64plus-GLideN64/mupen64plus-gui/interface/core_interface.cpp:162:70: error: 'QString' does not refer to a value
        rval = (*CoreStartup)(CORE_API_VERSION, NULL /*Config dir*/, QString coreDir(bundlepath).append("/Contents/Frameworks/"), (char*)"Core", DebugCallback, NULL, NULL);
                                                                     ^
/usr/local/Cellar/qt/5.10.0/lib/QtCore.framework/Headers/qmetatype.h:1926:1: note: declared here
QT_FOR_EACH_STATIC_CORE_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
^
/usr/local/Cellar/qt/5.10.0/lib/QtCore.framework/Headers/qmetatype.h:94:20: note: expanded from macro 'QT_FOR_EACH_STATIC_CORE_CLASS'
    F(QString, 10, QString) \
                   ^
/Users/stenapp/mupen64plus-GLideN64/mupen64plus-gui/interface/core_interface.cpp:228:33: error: 'QString' does not refer to a value
        QString corePath = QDir(QString coreDir(bundlepath).append("/Contents/Frameworks/").filePath(OSAL_DEFAULT_DYNLIB_FILENAME));
                                ^
/usr/local/Cellar/qt/5.10.0/lib/QtCore.framework/Headers/qmetatype.h:1926:1: note: declared here
QT_FOR_EACH_STATIC_CORE_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
^
/usr/local/Cellar/qt/5.10.0/lib/QtCore.framework/Headers/qmetatype.h:94:20: note: expanded from macro 'QT_FOR_EACH_STATIC_CORE_CLASS'
    F(QString, 10, QString) \
                   ^
3 errors generated.
make: *** [core_interface.o] Error 1
/Users/stenapp/mupen64plus-GLideN64/mupen64plus-gui/mainwindow.cpp:271:29: error: 'QString' does not refer to a value
    QString ini_path = QDir(QString iniDir(bundlePath).append("/Contents/Resources/mupen64plus-gui.ini");
                            ^
/usr/local/Cellar/qt/5.10.0/lib/QtGui.framework/Headers/qtextformat.h:56:7: note: declared here
class QString;
      ^
/Users/stenapp/mupen64plus-GLideN64/mupen64plus-gui/mainwindow.cpp:675:2: error: expected ';' at end of declaration
}
 ^
 ;
/Users/stenapp/mupen64plus-GLideN64/mupen64plus-gui/mainwindow.cpp:675:2: error: expected '}'
/Users/stenapp/mupen64plus-GLideN64/mupen64plus-gui/mainwindow.cpp:254:1: note: to match this '{'
{
^
3 errors generated.
[QString error.zip](https://github.com/m64p/mupen64plus-gui/files/1566080/QString.error.zip)


```

**Comment by StenApp** [comment]
I'm no Programmer so I leave it half finished, was never working for me and maybe never will
