### ISSUE TITLE
I love this front-end! THANK YOU!

### ISSUE THREAD

**Issue by Jakecheslekov** [m64p/mupen64plus-gui#42]
I rarely ever do this, but.... I've been having soooo much trouble trying to get mupen64plus/mupen64plus-ui-python to work, so so very annoying, always with these errors telling me I don't have sdl2 when I most certainly do...

Now, your front-end actually works - it compiles no problem, it has a nice UI, I can setup the controls from inside of it, I haven't had time to give it a go yet but just after installing & inspecting it, it looks great! 
Thank you very much! Your work is seriously appreciated!!

**Comment by loganmc10** [comment]
Thank you very much :) I'm glad you've enjoyed it
