### ISSUE TITLE
(Report) Can't run SM64 Last Impact

### ISSUE THREAD

**Issue by mickey1007** [m64p/mupen64plus-gui#46]
Dear Support,

I can't run SM64 Last Impact V1.2.z64 file. It loads but showing white screen only. Any help?

**Comment by loganmc10** [comment]
SM64 Last Impact is not supported. It is a ROM hack that was designed for Project64, you should use that emulator to run this game.

SM64 Last Impact isn't a "true" N64 game, it doesn't work on a real console. It only works with Project64
