### ISSUE TITLE
ZIP support broken

### ISSUE THREAD

**Issue by Anunkas** [m64p/mupen64plus-gui#47]
Starting a game from a ZIP file does not work.
Example: Pack test ROM (from M64Py for example) m64p_test_rom.v64 into a ZIP. Then use drag&drop or the menu to open the ZIP file. Log file says:

Core Error: open_rom(): not a valid ROM image
GUI Error: core failed to open ROM image file 'C:/Users/Anunkas/Desktop/mupen64plus/m64p_test_rom.zip'.

Using newest build from Aug 10 2018.
Running Windows 10 64 bit.

**Comment by loganmc10** [comment]
Can you grab the latest build from the website and try it again? I updated it today

**Comment by Anunkas** [comment]
It seems to work again. But I only tested the test ROM file.
Thanks! :)
