### ISSUE TITLE
QEGLPlatformContext: Failed to create context: 3009

### ISSUE THREAD

**Issue by Askmewho** [m64p/mupen64plus-gui#50]
QEGLPlatformContext: Failed to create context: 3009 on raspberry pi 3 under opnegl driver. maybe a newer opengl version needed?

**Comment by loganmc10** [comment]
Yeah I don't think the Raspberry Pi supports OpenGL 3.3.

You can try launching with the --gles option like:

./mupen64plus-gui --gles

That should create a GLES context that may work, though I haven't tried it in a while
