### ISSUE TITLE
Fullscreen not using specified resolution

### ISSUE THREAD

**Issue by teconmoon** [m64p/mupen64plus-gui#52]
Hi there, I am working with getting m64p setup with my games, and I noted that although my video settings are set as follows, when going fullscreen the render resolution is way too high.

![image](https://user-images.githubusercontent.com/46909426/51504551-76fb6e80-1d96-11e9-8a33-5b977c854aee.png)

![image](https://user-images.githubusercontent.com/46909426/51504658-effac600-1d96-11e9-9b18-3de96ac1e8f5.png)

My computer can't handle all games at this high a resolution, can you advise if this is intended behavior? I can't find another way to control the render rate. Thanks!

**Comment by loganmc10** [comment]
In the video plug-in there is an option called "UseNativeResFactor" if you set that to 1 it means "games original resolution", 2 is 2x original resolution, etc...

By default it will scale up to your display resolution

**Comment by teconmoon** [comment]
Got it, thanks! Hovering over the ScreenWidth option showed "Width of output window or fullscreen width" so I automatically assumed that's what I was looking for. Thanks for the clarification!

**Comment by loganmc10** [comment]
Yeah it could be clearer, that option basically specifies the default windowed resolution
