### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by fprimex** [m64p/mupen64plus-gui#9]
Making a generic ticket to push this through to completion as I think it's really close, and just needs some patches. I filed https://github.com/gonetz/GLideN64/issues/1405 which resolved building master of GLideN64 on Mac. There are a few other patches that are needed, which may be specific to the way I'm building everything.

MacOS Sierra 10.12.3 (16D32), MacBook Air (11-inch, Early 2015), Xcode Version 8.2.1 (8C1002), clang Apple LLVM version 8.0.0 (clang-800.0.42.1). I'm using `nasm` and `sdl2` from homebrew:

```
brew install nasm
brew install sdl2 sdl2_gfx sdl2_image sdl2_mixer sdl2_net sdl2_ttf
```

The following is needed for `mupen64plus-audio-sdl`:

```
$ git diff
diff --git a/projects/unix/Makefile b/projects/unix/Makefile
index 4a75104..71c75b1 100755
--- a/projects/unix/Makefile
+++ b/projects/unix/Makefile
@@ -127,10 +127,10 @@ ifeq ($(OS), OSX)
 
   ifeq ($(CPU), X86)
     ifeq ($(ARCH_DETECTED), 64BITS)
-      CFLAGS += -pipe -arch x86_64 -mmacosx-version-min=10.5 -isysroot $(OSX_SDK_PATH)
+      CFLAGS += -pipe -arch x86_64 -mmacosx-version-min=10.6 -isysroot $(OSX_SDK_PATH)
       LDLIBS += -ldl
     else
-      CFLAGS += -pipe -mmmx -msse -fomit-frame-pointer -arch i686 -mmacosx-version-min=10.5 -isysroot $(OSX_SDK_PATH)
+      CFLAGS += -pipe -mmmx -msse -fomit-frame-pointer -arch i686 -mmacosx-version-min=10.6 -isysroot $(OSX_SDK_PATH)
       LDLIBS += -ldl -read_only_relocs suppress
     endif
   endif
```

Same is needed for `mupen64plus-input-sdl`:

```
[brent@titan-ae:~/code/loganmc10/mupen64plus-GLideN64/mupen64plus-input-sdl]
$ git diff
diff --git a/projects/unix/Makefile b/projects/unix/Makefile
index 5eedcba..0eecc5d 100755
--- a/projects/unix/Makefile
+++ b/projects/unix/Makefile
@@ -127,10 +127,10 @@ ifeq ($(OS), OSX)
 
   ifeq ($(CPU), X86)
     ifeq ($(ARCH_DETECTED), 64BITS)
-      CFLAGS += -arch x86_64 -mmacosx-version-min=10.5 -isysroot $(OSX_SDK_PATH)
+      CFLAGS += -arch x86_64 -mmacosx-version-min=10.6 -isysroot $(OSX_SDK_PATH)
       LDLIBS += -ldl
     else
-      CFLAGS += -mmmx -msse -fomit-frame-pointer -arch i686 -mmacosx-version-min=10.5 -isysroot $(OSX_SDK_PATH)
+      CFLAGS += -mmmx -msse -fomit-frame-pointer -arch i686 -mmacosx-version-min=10.6 -isysroot $(OSX_SDK_PATH)
       LDLIBS += -ldl -read_only_relocs suppress
     endif
   endif
```

Same is needed for `mupen64plus-ui-console`:

```
[brent@titan-ae:~/code/loganmc10/mupen64plus-GLideN64/mupen64plus-ui-console]
$ git diff
diff --git a/projects/unix/Makefile b/projects/unix/Makefile
index f69cb66..23772cb 100755
--- a/projects/unix/Makefile
+++ b/projects/unix/Makefile
@@ -98,9 +98,9 @@ ifeq ($(OS), OSX)
 
   ifeq ($(CPU), X86)
     ifeq ($(ARCH_DETECTED), 64BITS)
-      CFLAGS += -pipe -arch x86_64 -mmacosx-version-min=10.5 -isysroot $(OSX_SDK_PATH)
+      CFLAGS += -pipe -arch x86_64 -mmacosx-version-min=10.6 -isysroot $(OSX_SDK_PATH)
     else
-      CFLAGS += -pipe -mmmx -msse -fomit-frame-pointer -arch i686 -mmacosx-version-min=10.5 -isysroot $(OSX_SDK_PATH)
+      CFLAGS += -pipe -mmmx -msse -fomit-frame-pointer -arch i686 -mmacosx-version-min=10.6 -isysroot $(OSX_SDK_PATH)
     endif
   endif
 endif
```

I used the revisions used by [mupen64plus-GLideN64](https://github.com/m64p/mupen64plus-GLideN64) with the exception that `GLideN64` and `mupen64plus-gui` are both at master.

MacOS also has an rpath warning which can be shut up with: `set(CMAKE_MACOSX_RPATH 1)`.

End result:

![screen shot 2017-03-06 at 3 59 35 pm](https://cloud.githubusercontent.com/assets/614790/23636036/38460f54-02a1-11e7-9787-a13bf53b4ba7.png)

It only works the first time and there are some weird issues. The `core library path` option does not allow me to select a directory. I made symlinks everywhere (lol) and eventually it did work. BUT, it only works one time and I don't know why. After that it says the core library can't be loaded. If I rebuild (remove the `.app` and `make`, then recopy it over) it works again one time. Must be something in the init code for the GUI.

The `dylib` files should probably go in the `.app` package, I think in `Resources`, and default to that path on MacOS.

The audio lagged a bit in the Mario 64 intro that's in the screen shot. Probably due to my laptop more than anything, but there may be performance issues in general.

I'll be working up a PR for your build script that automates the MacOS build now that I've got this working. I'll try to figure out the paths thing and the "only runs once" thing unless you have ideas on this.

Cheers!

**Comment by loganmc10** [comment]
Thanks for all the help, I don't have any access to a Mac, so I'm unable to test any of this. If there are things needed for the modules like mupen64plus-audio-sdl, you'll need to submit PR's to those repos.

I'm not sure why it won't let you select the core library path, by the way, the core library path is the path to the file, not the directory it's in, so you should be selecting "libmupen64plus.dylib" in that dialog. In the "plugin dir path" setting you should be selecting a directory that contains the plugins.

If you are able to find the path to the settings file for mupen64plus-gui it would be helpful. When you select the core library path and the plugin dir path, it saves your choices to a settings file, so it would be helpful to see what values it is saving.

Based on my reading (I Googled "Where does Qsettings store values on Mac"), it should either be in ```$HOME/Library/Preferences/``` or ```$HOME/.config/```, and you'll be looking for a file called ```mupen64plus/gui.conf``` or something like that.

**Comment by fprimex** [comment]
>  the core library path is the path to the file, not the directory it's in, so you should be selecting "libmupen64plus.dylib"

I realized that but also could not select any `.dylib`. The issue ended up being a typo: https://github.com/m64p/mupen64plus-gui/pull/10

Just so it's here in the ticket, I do have `~/.config/mupen64plus/mupen64plus.cfg`. Doesn't look like I have anything in `~/Library/Preferences` for this app. There was no `gui.conf` that I came across... Should I definitely have one somewhere?

Also: [Video](https://1drv.ms/v/s!AjDZIIpQcHVngRcQGPLSlFQmXKhv) (8.3MB, with screenflow demo/trial)

I noticed also that the settings for plugins don't load unless I load a ROM first. There's a few other things, like if the core library can't be found when the settings window closes, another main window is created. I'll try to work that stuff up as I can. Going to probably be slow going for me for a bit.

**Comment by loganmc10** [comment]
Thanks for fixing that typo. The plugin settings thing is unavoidable as far as I can tell. The plugins don't populate the settings file until they run, and they don't run until a game is played, so you pretty much have to start a game to see what's in there.

Is the core library path and plugin for path kept after the app is closed? If they are persistent then the settings file must exist somewhere, that's where that information is stored

**Comment by fprimex** [comment]
They do persist. Aha, it's a plist file located at `~/Library/Preferences/com.mupen64plus.gui.plist`.

I wonder if you could go overboard and have some tiny, minimal homebrew ROM that loads quickly and exits in the background to populate the settings. Could be risky if the settings or plugins are broken, but maybe there's a way to trap everything that could go wrong.

**Comment by loganmc10** [comment]
Yes something like that could be done, tomorrow I'll look at how m64py handles that issue, I'm not sure what they do

**Comment by loganmc10** [comment]
> like if the core library can't be found when the settings window closes, another main window is created.

It's not actually another main window, it's an empty settings window, I've fixed that here: https://github.com/m64p/mupen64plus-gui/commit/3d654b5f312b4e74059a446991a79b12edb87659

As far as the settings go, the hacky homebrew ROM thing is really the only solution, the mupen64plus API says:

> Both the core library and the plugin library must already be initialized with the CoreStartup()/PluginStartup() functions, and a ROM must be open

So you have to have a ROM to attach the plugin. I don't really like the idea of bundling some homebrew ROM, I'm ok with how it works now, it's just the way the mupen64plus API works. The core settings are available right away, it's just the audio and video plugins that need a ROM to initialize.

**Comment by loganmc10** [comment]
Actually I guess it's possible to load ```PluginStartup``` before a ROM is open, but it's still up to the plugin to decide when to load configs. For instance, GLideN64 loads the configuration at "ROMOpen", but Rice Video does it at PluginStartup.

Anyway I'll look into running PluginStartup before a ROM opens, that should cover most the plugins, but there will be some exceptions, like GLideN64

**Comment by loganmc10** [comment]
Ok I've updated it (f7a81f39d9f32589775754db48c1e3e9fd0953e2) to get the configuration values from the plugin before a ROM starts. Like I mentioned, this doesn't work with GLideN64, since it starts up the configuration on ROM open, but it does work for Rice Video and Audio-SDL, probably other plugins as well.

**Comment by fprimex** [comment]
IMO it may be worth an issue/feature request with GLideN64 to make it possible. I fired up M64PY to configure my Saitek P880 this evening and looks like there are some wild input issues. I'm going to try it on other platforms and see if it's Mac specific, or specific to this particular gamepad. Hope not, as my Saitek has been my go to for N64.

**Comment by loganmc10** [comment]
The reason GLideN64 runs the config code after the ROM is open is because it modifies some of the config values based on what ROM it is (basically it applies some config hacks depending on the game). That's not to say it couldn't be re-written in order to work differently, but it won't be as simple as moving a function to another location.

**Comment by fprimex** [comment]
Haven't figured out the Saitek issue yet, but I got a great deal on an Xbox One Bluetooth controller tonight. It works with MacOS out of the box, and I was able to configure it with M64PY and actually play SM64 with it from the GUI!

On the GLideN64 config stuff, I was wondering if it'd be worth entertaining the idea of requesting they provide a function to call to get the "normal" settings (what would load if there was no specific override), and then if they get overridden by game specific settings, show that in the config UI after a ROM is loaded in another column.

So for each GLideN64 setting, you'd have a column with headings "setting", "value", and "ROM override value", and if any value was not the same after ROM load, there would be an entry for that setting's row.

**Comment by loganmc10** [comment]
The custom ROM settings aren't related to the settings you can change in the GUI, they are more like hacks that get enabled for certain games, it's just that GLideN64 enables these hacks as part of the Config loading process.

Are there other things that need to get worked on with this GUI for Mac OS support? Or does it all seem to work normal now?

**Comment by fprimex** [comment]
I need to go completely through the whole build fresh again and list all of the things that might need changes. Off the top of my head:

* Because I use newer SDL2 from homebrew, the plugins have to have a compiler argument modified (macos min version bumped from 10.5 to 10.6).

* The pointer to the revision of GLideN64 needs to be beyond the version with the mac fixes.

* The shell script to build the App needs to be updated with Mac support (dylib extension handling, copying things into the App)

* Need to figure out where to put everything in the App. I think binaries go in MacOS and configs are _supposed_ to go in Resources, but if we split them I'm not sure how that works, exactly.

* Need to default the core lib file and plugins directory to the MacOS directory.

If you're looking to cut a release soon, I'd say go ahead with Windows and Linux and I can try to get to this stuff for a later release. I've been tied up with work, kids, and giving a python talk tomorrow.

**Comment by loganmc10** [comment]
No I'm not planning on releasing anything soon, but this repo (mupen64plus-gui) is just for the GUI, which anybody can compile on their own, most of the issues you are talking about are referring to this repo: https://github.com/m64p/mupen64plus-GLideN64, which is where that build script lives.

I use that build script to upload binary builds to http://m64p.s3-website-us-east-1.amazonaws.com/, and right now there are Windows and Linux builds.

**Comment by loganmc10** [comment]
And by the way, the version of GLideN64 used in the build script at https://github.com/m64p/mupen64plus-GLideN64 should contain the Mac OS fixes.

**Comment by fprimex** [comment]
We can close this out if you'd like. I was kind of using it as a personal TODO list, which is probably not a great use the issues section of the repo.

**Comment by loganmc10** [comment]
No it's fine you can leave it open, I was just trying to see if there is anything else that needs to be fixed specific to this GUI, but it looks like all that is left is some stuff to do with where to put the files on a Mac, so I'll leave that up to you.

**Comment by azoreseuropa** [comment]
I would like to try to compile it for macOS and I got this:

git clone https://github.com/m64p/mupen64plus-gui.git
cd mupen64plus-gui
mkdir build
cd build
cmake ../ 
make 

And I got an error:

CMake Error: The source directory "/Users/myname/mupen64plus-gui" does not appear to contain CMakeLists.txt.

**Comment by loganmc10** [comment]
You should be using ```qmake``` not ```cmake```

**Comment by azoreseuropa** [comment]
-bash: qmake: command not found

**Comment by loganmc10** [comment]
I don't have a Mac, but you'll need to install qmake, which is part of Qt. This application is written in Qt. I'm not sure how that is accomplished on a Mac

**Comment by azoreseuropa** [comment]
I understand.. I did this:

brew install qt

qt is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version

I don't want to type --force because I have other linked to opt so what should I do ?

**Comment by loganmc10** [comment]
These are questions specific to Mac and the Homebrew system, which I am unfamiliar with. @fprimex seems to have got this working, so he might have some answers.

**Comment by azoreseuropa** [comment]
Okay.. I will wait for his answer. By the way, I already have QT5 installed. I compiled any emulators along with QT5 and don't have a problem. This emulator is the first one I have an error. Why this message said: 

-bash: qmake: command not found

**Comment by loganmc10** [comment]
If you know where Qt is installed, you should look inside the ```bin``` folder in that directory, there should be a program called ```qmake```.

**Comment by azoreseuropa** [comment]
No, I do not. I will wait for @fprimex.

**Comment by azoreseuropa** [comment]
By the way, I do this:
brew search qt

Warning: qt is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version
Antonios-MBP:build andradeandrade$ qmake ../
-bash: qmake: command not found
mynames-MBP:build myname$ qmake5 ../
-bash: qmake5: command not found
mynames-MBP:build myname$ qtmake ../
-bash: qtmake: command not found
mynames-MBP:build myname$ brew search qt
pyqt                qt@5.5              qtads               sqtop
qt ✔                qt@5.7              qtfaststart

QT is checked mark.

**Comment by fprimex** [comment]
Hi,

I am pushing my build script modifications here: https://github.com/m64p/mupen64plus-GLideN64/pull/1

which you should be able to use to get this compile going. I have unfortunately not worked on this in some time but I feel I should post my mac work so that perhaps others can push it over the finish line.

**Comment by loganmc10** [comment]
so @azoreseuropa to answer your main question, it looks like @fprimex is using ```/usr/local/Cellar/qt5/*/bin/qmake```

**Comment by azoreseuropa** [comment]
Hi fprimex,

Okay.. Before I type qmake ../ 

what should I type in terminal so I can tell it to use qmake ?

Loganmc10, yeah.. but I wonder how ? Hope he can help me with that.

**Comment by fprimex** [comment]
Made some progress: https://github.com/m64p/mupen64plus-GLideN64/pull/8

**Comment by fprimex** [comment]
I think the challenges are well understood now and all that's needed is follow-through. This project, `mupen64plus-gui`, works on Mac now (compiles & runs) regardless as to how it is eventually packaged, as discussed in the link above. See the above fork/PR for more info. Closing this out.

**Comment by fprimex** [comment]
@azoreseuropa I know it's been forever and sorry about that. If you are still wondering or if anyone else is reading, you need to install a bunch of stuff using homebrew.

```
brew install nasm
brew install sdl2 sdl2_gfx sdl2_image sdl2_mixer sdl2_net sdl2_ttf
```

For `qt` I can't remember if it is `brew install qt` or `brew install qt5` - one or the other. You need Qt 5.x for certain. Once I get everything tidied up I'll be submitting updates to the README and whatnot for MacOS compilation.

**Comment by fprimex** [comment]
Also, homebrew is here, if you've never used it before:

https://brew.sh

**Comment by azoreseuropa** [comment]
Thank you kindly. Been forever is better than neer. So thank you again! :D
